# LOCAL-FIRST Docker Compose (optional fallback only)
# Optimized for native macOS execution - use only if needed
version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
