name = "realmultillm"
version = "0.1.0"
description = "RealMultiLLM Next.js application"
license = "MIT"

[tool]
name = "RealMultiLLM"

[tool.scripts]
dev = "npm run dev"
build = "npm run build"
start = "npm start"

[env]
NODE_ENV = "development"
