# RealMultiLLM Netlify Configuration
# Target Environment: macOS 12+ | 2013 MacBook Pro (16GB) + 2022 M2 MacBook Air (8GB)

# 3-STEP DEPLOYMENT PLAN:
# 1. Configure memory-optimized build settings for Next.js
# 2. Set up secure environment variables handling
# 3. Add performance optimizations and security headers

[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  # Memory optimization: Allocate memory based on available resources
  NODE_OPTIONS = "--max-old-space-size=3072 --max-semi-space-size=128"
  # Disable telemetry for faster builds
  NEXT_TELEMETRY_DISABLED = "1"
  # Use production mode
  NODE_ENV = "production"
  # Default to SQLite for builds (will be overridden in production)
  DATABASE_URL = "file:./build.db"

# SECURITY NOTICE: 
# Set the following environment variables in the Netlify UI under "Environment variables":
# REQUIRED:
# - NEXTAUTH_SECRET (generate with `openssl rand -base64 32`)
# - NEXTAUTH_URL (your site URL, e.g., https://your-site.netlify.app)
# 
# OPTIONAL (for LLM features):
# - OPENAI_API_KEY
# - ANTHROPIC_API_KEY  
# - GOOGLE_AI_API_KEY
# - GROQ_API_KEY
# - HUGGINGFACE_TOKEN
# 
# DATABASE (for production):
# - DATABASE_URL (PostgreSQL connection string for production)
#
# OAUTH (if using social login):
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - GITHUB_CLIENT_ID
# - GITHUB_CLIENT_SECRET

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https://vercel.live;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://api.openai.com https://api.anthropic.com https://generativelanguage.googleapis.com https://api.groq.com https://huggingface.co;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    '''

# Optimize static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes security
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

# Redirect rules for better SEO
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Function timeout settings for API routes
[functions]
  node_bundler = "esbuild"
  # Extend timeout for LLM API calls
  "*" = { timeout = 30 }

# Build optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true