# AdvancePilot-Copilot: FIXED RealMultiLLM Netlify Configuration
# Target Environment: macOS 12+ | 2013 MacBook Pro (16GB) + 2022 M2 MacBook Air (8GB)
# Architecture: Next.js TypeScript with Multi-LLM API Integration + NextAuth + Prisma
#
# 3-STEP DEPLOYMENT PLAN:
# 1. BARRIER IDENTIFICATION: Fix base directory config and build command
# 2. DYNAMIC SYNERGY: Use official Netlify Next.js plugin for routing and serverless
# 3. PERFORMANCE OPTIMIZATION: Optimize memory and secure the app

[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXTAUTH_URL = "https://real-multi-llm.netlify.app"  # Update this to your actual site URL

# IMPORTANT: Set the following sensitive environment variables in the Netlify UI under "Environment variables":
# - OPENAI_API_KEY = " "
# - ANTHROPIC_API_KEY
# - GOOGLE_AI_API_KEY = " "
# - LLAMA_API_KEY (if using)
# - GITHUB_API_KEY (if using)
# - GROK_API_KEY (if using)
 - NEXTAUTH_SECRET = "+67MKOk8aZcQxYj7djM9K9HSYquiJ17Fk0JtJqWzxYY="  #(generate with `openssl rand -base64 32`)
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - GITHUB_CLIENT_ID
# - GITHUB_CLIENT_SECRET
# - DATABASE_URL (your Supabase PostgreSQL connection string)

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"