# RealMultiLLM Netlify Configuration
# Target Environment: macOS 12+ | 2013 MacBook Pro (16GB) + 2022 M2 MacBook Air (8GB)

# 3-STEP DEPLOYMENT PLAN:
# 1. Configure build settings for Next.js
# 2. Set up proper environment variables handling
# 3. Add security headers and performance optimizations

[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  # optimization: Allocate maximum memory for build process while leaving room for system
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Disable telemetry for faster builds
  NEXT_TELEMETRY_DISABLED = "1"
  # Use production mode
  NODE_ENV = "production"
  # scalability: Use environment variables from Netlify UI for sensitive values

# IMPORTANT: Set the following environment variables in the Netlify UI:
# - DATABASE_URL (PostgreSQL connection string)
# - NEXTAUTH_SECRET (generate with `openssl rand -base64 32`)
# - NEXTAUTH_URL (your site URL)
# - OPENAI_API_KEY, ANTHROPIC_API_KEY, GOOGLE_AI_API_KEY
# - OAuth credentials if using social login

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    # security: Add security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.openai.com https://api.anthropic.com https://generativelanguage.googleapis.com"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    # optimization: Add caching for static assets
    Cache-Control = "public, max-age=31536000, immutable"

# Optional: Create redirects if needed
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200