# AdvancePilot-Copilot Netlify Configuration
# 3-Step Plan:
# 1. Fix base directory configuration error (remove "Mmaster" reference)
# 2. Define proper build settings for TypeScript/Next.js project
# 3. Optimize for performance and SPA routing

[build]
  # Base directory fix - deploy from repository root (was incorrectly set to "Mmaster")
  base = ""
  
  # Build command optimization for TypeScript/Next.js environment
  command = "npm ci && npm run build"
  
  # Publish directory - standard Next.js output
  publish = "dist"

[build.environment]
  # Performance optimization - use latest stable Node.js
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
  # Memory optimization for 8GB M2 MacBook Air compatibility
  NODE_OPTIONS = "--max-old-space-size=4096"

# SPA routing configuration for dynamic synergy
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# API routes handling (if using Next.js API)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers for scalability
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Performance optimization - cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ✅ Configuration complete - addresses deployment failure root cause
# Self-audit: Fixed "Mmaster" directory error, added performance optimizations,
# included security headers, and configured proper routing for TypeScript project