# RealMultiLLM Netlify Configuration
# Optimized for macOS development: 2013 MacBook Pro (16GB) + 2022 M2 MacBook Air (8GB)
# Security-first configuration with no hardcoded secrets

[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  # Memory optimization for 8GB RAM constraint
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Disable telemetry for faster builds
  NEXT_TELEMETRY_DISABLED = "1"
  # Production environment
  NODE_ENV = "production"

# Required environment variables (set in Netlify UI - NOT in this file)
# SECURITY: All sensitive values must be set in Netlify dashboard
# 
# Database:
# - DATABASE_URL (PostgreSQL connection string from your provider)
# 
# Authentication:
# - NEXTAUTH_SECRET (generate with: openssl rand -base64 32)
# - NEXTAUTH_URL (will be auto-set by Netlify)
# 
# OAuth Providers:
# - GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET
# - GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET
# 
# AI API Keys:
# - OPENAI_API_KEY
# - ANTHROPIC_API_KEY  
# - GOOGLE_AI_API_KEY

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Enhanced CSP for better security
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: blob:;
      font-src 'self' data:;
      connect-src 'self' https://api.openai.com https://api.anthropic.com https://generativelanguage.googleapis.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
    """

# Optimize static asset caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# API route handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200