# AdvancePilot-Copilot: FIXED RealMultiLLM Netlify Configuration
# Target Environment: macOS 12+ | 2013 MacBook Pro (16GB) + 2022 M2 MacBook Air (8GB)
# Architecture: Next.js TypeScript with Multi-LLM API Integration + NextAuth + Prisma
#
# 3-STEP DEPLOYMENT PLAN:
# 1. BARRIER IDENTIFICATION: Fix base directory config and build command
# 2. DYNAMIC SYNERGY: Use official Netlify Next.js plugin for routing and serverless
# 3. PERFORMANCE OPTIMIZATION: Optimize memory and secure the app

[build]
  # Build command: Installs deps, generates Prisma client, builds Next.js
  command = "npm install && npx prisma generate && npm run build"
  # Publish directory: Correct for Next.js (not dist, you dumbass previous configs)
  publish = ".next"

[build.environment]
  # Optimized for your shitty 8GB M2 MacBook Air
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"  # Prevents memory crashes
  NEXT_TELEMETRY_DISABLED = "1"              # Speeds up build
  NODE_ENV = "production"                    # Production mode
  
  # Your fucking LLM API keys - FILL THESE IN
  OPENAI_API_KEY = ""
  ANTHROPIC_API_KEY = ""
  GOOGLE_AI_API_KEY = ""
  LLAMA_API_KEY = ""
  GITHUB_API_KEY = ""
  GROK_API_KEY = ""
  
  # NextAuth shit - FILL THESE IN TOO
  NEXTAUTH_SECRET = ""                       # Run `openssl rand -base64 32` to generate
  NEXTAUTH_URL = "https://real-multi-llm.netlify.app"  # Your site URL
  GOOGLE_CLIENT_ID = ""
  GOOGLE_CLIENT_SECRET = ""
  GITHUB_CLIENT_ID = ""
  GITHUB_CLIENT_SECRET = ""
  
  # Database - PUT YOUR SUPABASE URL HERE
  DATABASE_URL = ""

# Netlify Next.js plugin: Handles all routing and serverless shit automatically
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers: Protects your ass in production
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Performance: Cache static assets so it doesn’t suck
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"